//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzXmpp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzXmpp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is disabled..
        /// </summary>
        internal static string XmppErrorCode_AccountDisabled {
            get {
                return ResourceManager.GetString("XmppErrorCode_AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication was aborted by the host..
        /// </summary>
        internal static string XmppErrorCode_AuthenticationAborted {
            get {
                return ResourceManager.GetString("XmppErrorCode_AuthenticationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication with the host failed..
        /// </summary>
        internal static string XmppErrorCode_AuthenticationFailed {
            get {
                return ResourceManager.GetString("XmppErrorCode_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has sent XML that cannot be processed..
        /// </summary>
        internal static string XmppErrorCode_BadFormat {
            get {
                return ResourceManager.GetString("XmppErrorCode_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has sent a namespace prefix that is unsupported..
        /// </summary>
        internal static string XmppErrorCode_BadNamespacePrefix {
            get {
                return ResourceManager.GetString("XmppErrorCode_BadNamespacePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is closing the active stream for this entity because a new stream has been initiated that conflicts with the existing stream..
        /// </summary>
        internal static string XmppErrorCode_Conflict {
            get {
                return ResourceManager.GetString("XmppErrorCode_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has not generated any traffic over the stream for some period of time..
        /// </summary>
        internal static string XmppErrorCode_ConnectionTimeout {
            get {
                return ResourceManager.GetString("XmppErrorCode_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account credentials have expired..
        /// </summary>
        internal static string XmppErrorCode_CredentialsExpired {
            get {
                return ResourceManager.GetString("XmppErrorCode_CredentialsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption is required to authenticate..
        /// </summary>
        internal static string XmppErrorCode_EncryptionRequired {
            get {
                return ResourceManager.GetString("XmppErrorCode_EncryptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;to&apos; attribute provided by the initiating entity in the stream header corresponds to a hostname that is no longer hosted by the server..
        /// </summary>
        internal static string XmppErrorCode_HostGone {
            get {
                return ResourceManager.GetString("XmppErrorCode_HostGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;to&apos; attribute provided by the initiating entity in the stream header does not correspond to a hostname that is hosted by the server..
        /// </summary>
        internal static string XmppErrorCode_HostUnknown {
            get {
                return ResourceManager.GetString("XmppErrorCode_HostUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stanza sent between two servers lacks a &apos;to&apos; or &apos;from&apos; attribute (or the attribute has no value)..
        /// </summary>
        internal static string XmppErrorCode_ImproperAddressing {
            get {
                return ResourceManager.GetString("XmppErrorCode_ImproperAddressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has experienced a misconfiguration or an otherwise-undefined internal error that prevents it from servicing the stream..
        /// </summary>
        internal static string XmppErrorCode_InternalServerError {
            get {
                return ResourceManager.GetString("XmppErrorCode_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JID or hostname provided in a &apos;from&apos; address does not match an authorized JID..
        /// </summary>
        internal static string XmppErrorCode_InvalidFrom {
            get {
                return ResourceManager.GetString("XmppErrorCode_InvalidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream ID or dialback ID is invalid or does not match an ID previously provided..
        /// </summary>
        internal static string XmppErrorCode_InvalidID {
            get {
                return ResourceManager.GetString("XmppErrorCode_InvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The impersonation identity is incorrect..
        /// </summary>
        internal static string XmppErrorCode_InvalidImpersonation {
            get {
                return ResourceManager.GetString("XmppErrorCode_InvalidImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication mechanism is invalid..
        /// </summary>
        internal static string XmppErrorCode_InvalidMechanism {
            get {
                return ResourceManager.GetString("XmppErrorCode_InvalidMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streams namespace name is something other than the required standard namespace..
        /// </summary>
        internal static string XmppErrorCode_InvalidNamespace {
            get {
                return ResourceManager.GetString("XmppErrorCode_InvalidNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has sent invalid XML over the stream to a server that performs validation..
        /// </summary>
        internal static string XmppErrorCode_InvalidXml {
            get {
                return ResourceManager.GetString("XmppErrorCode_InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is malformed..
        /// </summary>
        internal static string XmppErrorCode_MalformedRequest {
            get {
                return ResourceManager.GetString("XmppErrorCode_MalformedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication mechanism is too weak..
        /// </summary>
        internal static string XmppErrorCode_MechanismTooWeak {
            get {
                return ResourceManager.GetString("XmppErrorCode_MechanismTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has attempted to send data before the stream has been authenticated, or otherwise is not authorized to perform an action related to stream negotiation..
        /// </summary>
        internal static string XmppErrorCode_NotAuthorized {
            get {
                return ResourceManager.GetString("XmppErrorCode_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has violated some local service policy..
        /// </summary>
        internal static string XmppErrorCode_PolicyViolation {
            get {
                return ResourceManager.GetString("XmppErrorCode_PolicyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unable to properly connect to a remote entity that is required for authentication or authorization..
        /// </summary>
        internal static string XmppErrorCode_RemoteConnectionFailed {
            get {
                return ResourceManager.GetString("XmppErrorCode_RemoteConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required entity has sent a required feature that is not supported..
        /// </summary>
        internal static string XmppErrorCode_RequiredFeatureUnknown {
            get {
                return ResourceManager.GetString("XmppErrorCode_RequiredFeatureUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server lacks the system resources necessary to service the stream..
        /// </summary>
        internal static string XmppErrorCode_ResourceConstraint {
            get {
                return ResourceManager.GetString("XmppErrorCode_ResourceConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has attempted to send restricted XML features..
        /// </summary>
        internal static string XmppErrorCode_RestrictedXml {
            get {
                return ResourceManager.GetString("XmppErrorCode_RestrictedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server will not provide service to the initiating entity but is redirecting traffic to another host..
        /// </summary>
        internal static string XmppErrorCode_SeeOtherHost {
            get {
                return ResourceManager.GetString("XmppErrorCode_SeeOtherHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown stanza error..
        /// </summary>
        internal static string XmppErrorCode_Stanza {
            get {
                return ResourceManager.GetString("XmppErrorCode_Stanza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is being shut down and all active streams are being closed..
        /// </summary>
        internal static string XmppErrorCode_SystemShutdown {
            get {
                return ResourceManager.GetString("XmppErrorCode_SystemShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is temporarily unavailable..
        /// </summary>
        internal static string XmppErrorCode_TemporaryAuthFailure {
            get {
                return ResourceManager.GetString("XmppErrorCode_TemporaryAuthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while communicating with the XMPP server..
        /// </summary>
        internal static string XmppErrorCode_Unknown {
            get {
                return ResourceManager.GetString("XmppErrorCode_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream was not recognized..
        /// </summary>
        internal static string XmppErrorCode_UnrecognizedStream {
            get {
                return ResourceManager.GetString("XmppErrorCode_UnrecognizedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initiating entity has encoded the stream in an encoding that is not supported by the server..
        /// </summary>
        internal static string XmppErrorCode_UnsupportedEncoding {
            get {
                return ResourceManager.GetString("XmppErrorCode_UnsupportedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initiating entity has sent a first-level child of the stream that is not supported by the server..
        /// </summary>
        internal static string XmppErrorCode_UnsupportedStanzaType {
            get {
                return ResourceManager.GetString("XmppErrorCode_UnsupportedStanzaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;version&apos; attribute provided by the initiating entity in the stream header specifies a version of XMPP that is not supported by the server..
        /// </summary>
        internal static string XmppErrorCode_UnsupportedVersion {
            get {
                return ResourceManager.GetString("XmppErrorCode_UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initiating entity has sent XML that is not well-formed..
        /// </summary>
        internal static string XmppErrorCode_XmlNotWellFormed {
            get {
                return ResourceManager.GetString("XmppErrorCode_XmlNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate before attempting this request..
        /// </summary>
        internal static string XmppStanzaErrorCode_Authenticate {
            get {
                return ResourceManager.GetString("XmppStanzaErrorCode_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has failed..
        /// </summary>
        internal static string XmppStanzaErrorCode_Cancel {
            get {
                return ResourceManager.GetString("XmppStanzaErrorCode_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has succeeded..
        /// </summary>
        internal static string XmppStanzaErrorCode_Continue {
            get {
                return ResourceManager.GetString("XmppStanzaErrorCode_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the request and try again..
        /// </summary>
        internal static string XmppStanzaErrorCode_Modify {
            get {
                return ResourceManager.GetString("XmppStanzaErrorCode_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait and re-attempt the request..
        /// </summary>
        internal static string XmppStanzaErrorCode_Wait {
            get {
                return ResourceManager.GetString("XmppStanzaErrorCode_Wait", resourceCulture);
            }
        }
    }
}
